version: "{build}"

image:
  - Visual Studio 2015
  - Ubuntu

environment:
  nodejs_version: "11"

stack: node 10

matrix:
  fast_finish: true

install:
  - ps: |
      if ($isWindows) {
        Install-Product node $env:nodejs_version
      }
  - cmd: choco install firefox
  - cmd: choco install chromium

before_test:
  - node --version
  - npm --version
  - npm install

test_script:
  - cmd: npm test
  - sh: xvfb-run npm test

build: off
